server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.53.161:3306/netdisk?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location:
      file-size-threshold: 0
      resolve-lazily: false
  web:
    resources:
      static-locations: /META-INF/resources/, classpath:/static/, classpath:/templates/, classpath:/public/
  mvc:
    static-path-pattern: /**

mybatis:
  typeAliasesPackage: com.yx.entity
  mapperLocations: classpath:mapper/*Dao.xml
  #configLocation: classpath:/mybatis-config.xml